compilar :
	g++ Qs/main.cpp -Wall -o Quicksort
	g++ Ms/main.cpp -Wall -o Mergesort

clean :
	rm Quicksort Mergesort
fullclean : 
	rm Quicksort Mergesort quickSort.txt mergesort.txt

Quick :
	./Quicksort

Merge : 
	./Mergesort
